import { Goal, Bill, Purchase, SavingsDeposit, AppData } from './types';
import { format, subDays, addDays } from 'date-fns';

const today = new Date();
const fmt = (d: Date) => format(d, 'yyyy-MM-dd');

export const mockData: any = {
  totalSavings: 4850,
  goals: [
    {
      id: 'g1',
      name: 'MacBook Pro',
      icon: '💻',
      targetAmount: 3000,
      currentAmount: 1800,
      color: '#6366f1',
      createdAt: fmt(subDays(today, 60)),
      deadline: fmt(addDays(today, 45)),
      completed: false,
    },
    {
      id: 'g2',
      name: 'Dream Vacation',
      icon: '✈️',
      targetAmount: 5000,
      currentAmount: 2100,
      color: '#ec4899',
      createdAt: fmt(subDays(today, 90)),
      deadline: fmt(addDays(today, 120)),
      completed: false,
    },
    {
      id: 'g3',
      name: 'Emergency Fund',
      icon: '🛡️',
      targetAmount: 10000,
      currentAmount: 6500,
      color: '#10b981',
      createdAt: fmt(subDays(today, 180)),
      completed: false,
    },
    {
      id: 'g4',
      name: 'New Gaming Setup',
      icon: '🎮',
      targetAmount: 1500,
      currentAmount: 1500,
      color: '#f59e0b',
      createdAt: fmt(subDays(today, 120)),
      deadline: fmt(subDays(today, 2)),
      completed: true,
      completedAt: fmt(subDays(today, 2)),
    },
  ],
  bills: [
    {
      id: 'b1',
      name: 'Netflix',
      amount: 15.99,
      dueDate: fmt(addDays(today, 3)),
      paid: false,
      recurring: true,
      category: 'subscriptions',
    },
    {
      id: 'b2',
      name: 'Rent',
      amount: 1200,
      dueDate: fmt(addDays(today, 7)),
      paid: false,
      recurring: true,
      category: 'rent',
    },
    {
      id: 'b3',
      name: 'Electricity',
      amount: 85,
      dueDate: fmt(subDays(today, 2)),
      paid: true,
      recurring: true,
      category: 'utilities',
      paidAt: fmt(subDays(today, 3)),
    },
    {
      id: 'b4',
      name: 'Spotify',
      amount: 9.99,
      dueDate: fmt(addDays(today, 15)),
      paid: false,
      recurring: true,
      category: 'subscriptions',
    },
    {
      id: 'b5',
      name: 'Internet',
      amount: 60,
      dueDate: fmt(addDays(today, 1)),
      paid: false,
      recurring: true,
      category: 'utilities',
    },
    {
      id: 'b6',
      name: 'Gym Membership',
      amount: 45,
      dueDate: fmt(addDays(today, 20)),
      paid: false,
      recurring: true,
      category: 'other',
    },
  ],
  purchases: [
    {
      id: 'p1',
      name: 'Starbucks Coffee',
      amount: 6.5,
      category: 'food',
      date: fmt(today),
      note: 'Morning coffee',
    },
    {
      id: 'p2',
      name: 'Uber',
      amount: 12.3,
      category: 'transport',
      date: fmt(today),
    },
    {
      id: 'p3',
      name: 'Lunch',
      amount: 14.5,
      category: 'food',
      date: fmt(today),
    },
    {
      id: 'p4',
      name: 'Movie Tickets',
      amount: 28.0,
      category: 'entertainment',
      date: fmt(subDays(today, 1)),
    },
    {
      id: 'p5',
      name: 'Amazon Order',
      amount: 54.99,
      category: 'shopping',
      date: fmt(subDays(today, 2)),
    },
    {
      id: 'p6',
      name: 'Grocery Shopping',
      amount: 87.45,
      category: 'food',
      date: fmt(subDays(today, 2)),
    },
    {
      id: 'p7',
      name: 'Gym Snacks',
      amount: 8.25,
      category: 'food',
      date: fmt(subDays(today, 3)),
    },
    {
      id: 'p8',
      name: 'React Course',
      amount: 29.99,
      category: 'other',
      date: fmt(subDays(today, 4)),
    },
  ],
  deposits: [
    { id: 'd1', goalId: 'g1', amount: 300, date: fmt(subDays(today, 5)), note: 'Monthly savings' },
    { id: 'd2', goalId: 'g2', amount: 200, date: fmt(subDays(today, 5)) },
    { id: 'd3', goalId: 'g3', amount: 500, date: fmt(subDays(today, 5)) },
    { id: 'd4', goalId: 'g1', amount: 150, date: fmt(subDays(today, 12)) },
    { id: 'd5', goalId: 'g2', amount: 350, date: fmt(subDays(today, 12)) },
  ],
};
